[green_agent]
image = "ghcr.io/agentbeats/tutorial-tau2-evaluator:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019af0e6-fc7a-7483-95da-441c352ae6ab"
name = "agent"
image = "ghcr.io/agentbeats/tutorial-tau2-agent:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
# Add your assessment config here
domain = "airline"
num_tasks = 3
